ministryofjustice/bichard7-next-tests

package.json
Updated `npm run test:auditlogs` command to exclude tests that are meant to run against the real PNC.
=> Update auditlogs npm command to exclude real pnc tests

features/142-trigger-reallocation/test.feature
This fixes e2e tests in the pipeline
=> fix: 🐛 e2e failing on typo

features/154-1040-result-no-breach-trigger/input-message.xml, package.json
The offence code which was being used for this test has since been removed and this was causing the tests to behave differently and fail. This replaces the code with another which would raise a trigger to make sure it doesn't when there's a 1040 result code so the test is still valid
=> Update the test case for test 154 as the offence code is no longer valid

steps/ui.js
With the `filter chips` on the defendant name field, the navigation breaks when using the [enter] key instead of explicitly clicking on the search button
=> Fix navigation for next UI search

features/108-offence-start-date-mismatch/test.feature, features/303-no-ho100332-and-ho100304/test.feature
- Offence 2 should not actually have a HO100332 raised so let's not test for it in test 303
- We don't raise triggger 18 if we have a matching error, only on resubmission
=> Update the tests slightly to deal with slight differences with core

Dockerfile
Build docker image script was failing because python package has been renamed to python3.
=> Fix build docker image due to python package

features/basic-login.feature
To support https://github.com/ministryofjustice/bichard7-next-ui/pull/328
=> Make basic login test check for triggers on the page, not PNC errors tab

features/500-case-lock-events/test.feature, features/501-trigger-resolved-events/test.feature
This was perviously disabled as it wasn't implemented in the new UI
=> Check exception unlocked event is generated

features/108-offence-start-date-mismatch/test.feature, features/295-duplicate-offences-one-added-in-court/test.feature, helpers/BrowserHelper.js
Don't set the manual sequence number to a nonexistent sequence in the test - this used to work in Bichard but now we throw an exception since it doesn't exist!
=> Fix test behaviour for manually adding an offence in court

.circleci/config.yml
This PR updates CircleCI config to:
- Use the latest ubuntu machine image (ubuntu-2204:2023.07.2)
- Use our latest NodeJS image (required to build message-forwarder, event-handler, and audit-log-api images)
- Use nvm to install the NodeJS runtime version in Core repo
=> Update ci images

e2eTestBuildspec.yml, features/121-force-calculation-from-court-code/test.feature, features/142-trigger-reallocation/test.feature, features/158-breach-results/test.feature, features/190-correcting-invalid-asn/test.feature, features/194-new-breach-offence-trigger-and-exception/test.feature, features/264-aint-results/test.feature, features/403-fix-exceptions/test.feature, features/404-fix-exceptions-and-triggers/test.feature, features/405-fix-exceptions-multiple-attempts/test.feature, features/409-pnc-resubmission-errors/test.feature, scripts/run-pipeline-tests.sh, step-definitions/old-cucumber-js.steps.js, step-definitions/old-utils/ui.js
- Adds a "When I return to the list" cucumber step because the return to list button changes depending on how long the backend takes to process data
- Enable the e2e tests in the pipeline to have an override for running all tests
- Make the role for running tests in CD last longer
=> Make the tests less timing dependent

characterisation/exceptions/HO100251.test.ts
When there is an invalid offence code format legacy Bichard raises HO100251 - 'Offence Code not recognised' but core raises HO100306 - 'Offence Code not found' exception, we decided that is an acceptable diviation, since HO100251 is an edge case and almost never happens in prod
=> Add characterisation test for HO100251 exception

features/296-result-text-disposal-text/test.feature, features/410-blank-manual-seq-added-in-court/test.feature, features/411-blank-manual-seq-match/test.feature, features/504-note-generation/test.feature
When exceptions are resolved in the new UI, the case incorrectly has a RESOLVED badge, even when the case has unresolved triggers.
- Remove incorrect scenarios 
- Enable tests for new UI that are running on a legacy application
=> Fix exception resolution tests that capturing incorrect behaviour

features/296-result-text-disposal-text/test.feature, features/410-blank-manual-seq-added-in-court/test.feature, features/411-blank-manual-seq-match/test.feature, features/504-note-generation/test.feature
This causes flaky tests on the new UI because Bichard may pick up and update the case status before the test navigates to the case list and checks the status.
=> Remove cucumber step that check submitted status

step-definitions/utils/ui.js
The delay seems to be more reliable on CI 🤷‍♂️
=> Go back the original delay

step-definitions/utils/ui.js
This prevents inputs from being not typed correctly; see below:
=> Add delay on input

utils/actions.next-ui.js
* `element.value = ''` does not trigger a change event in React. We need a change event.
=> Force a change event whilst clear an input field

characterisation/helpers/processMessage.ts, characterisation/helpers/processMessageBichard.ts, characterisation/helpers/processMessageCore.ts, characterisation/types/Phase.ts
Now that we've rewritten Phase 2, we want to enable characterisation tests for it.
- Add `phase` parameter in the `processMessage` functions for Bichard and Core.
- It defaults to Phase 1.
- For Bichard: send the message to the `HEARING_OUTCOME_PNC_UPDATE_QUEUE` queue if Phase 2 instead of `COURT_RESULT_INPUT_QUEUE`. I took the queue name from the [send to Phase 2 Conductor task](https://github.com/ministryofjustice/bichard7-next-core/blob/b6e2066d1584fa9e5d35a06c5b2ce38c2035e032/packages/core/conductor-tasks/bichard_phase_1/sendToPhase2.ts#L23), correct me if this isn't the right one!
- For Core: add the phase to POST request to test server API for Core.
- Update test server in Core to use the `phase` and return Phase 2 result as well.
https://dsdmoj.atlassian.net/browse/BICAWS7-3017
=> Add phase parameter for processing messages in characterisation tests

.circleci/config.yml
This PR updates CI config to use consistent namings for CI jobs and parameters.
=> Fix jobs and parameters naming in CI

.circleci/config.yml
- Used snake_case naming for jobs
- Renamed the `build` job to install_and_lint. Also, updated the job to run linter.
=> Fix CI jobs namings

.circleci/config.yml, README.md, package.json
The amount of times I've run the wrong command for characterisation tests for legacy Bichard is too damn high!
=> Add NPM scripts for legacy Bichard characterisation tests

utils/dummyUserData.js
Impact is only locally.
We use the same `generalhandler`, etc, in cypress tests locally. This fixes having to add  a visible force in the DB for a user (or delete a user) when running cypress tests locally.
=> Add visible force to all users

characterisation/exceptions/HO200112.test.ts, characterisation/test-data/HO200112/aho.xml.njk, characterisation/test-data/HO200112/pud.xml.njk
- I've only created tests for the happy path as I don't see any value in doing an unhappy path for the exceptions generated when validating operations as it's literally anything else i.e. "NOT this very specific journey through the code".
- Also, we'll have other characterisation tests for all the other exceptions raised in `validateOperations`.
- Worth noting the input message required multiple results for an offence to match the two operations required to generate the exception.
- Also the order of the results mattered!
https://dsdmoj.atlassian.net/browse/BICAWS7-3054
=> Add HO200112 characterisation tests

characterisation/exceptions/HO200114.test.ts
There are two scenarios in which a HO200114 exception can be raised:
1. when a SENDEF and SUBVAR operation are generated
2. when a SENDEF and PENHRG operation are generated
These operations are then validated within `validateOperations` and an exception is raised if they are found together.
Scenario 1 is the only possibility and only for a PncUpdateDataset.
This is because:
1. a SENDEF can only be generated if an offence result is a SENTENCE and NOT fixed penalty and there is NOT a PNC result which is 2007.
2. a SUBVAR can be generated if an offence result is JUDGEMENT WITH FINAL RESULT and NOT fixed penalty:
a. the input message is resubmitted e.g. PncUpdateDataset
b. or ALL PNC results are 2007
3. a SUBVAR can be generated if an offence result is a SENTENCE and there is at least ONE PNC …
=> Add HO200114 characterisation tests

characterisation/exceptions/HO200109/HO200109-APPHRD-DISARR.test.ts, characterisation/exceptions/HO200109/HO200109-APPHRD-NEWREM-CCR.test.ts, characterisation/exceptions/HO200109/HO200109-APPHRD-NEWREM.test.ts, characterisation/exceptions/HO200109/HO200109-APPHRD-PENHRG.test.ts, characterisation/exceptions/HO200109/HO200109-APPHRD-SENDEF.test.ts, characterisation/exceptions/HO200109/HO200109-APPHRD-SUBVAR.test.ts, characterisation/helpers/generatePhase2Message.ts, characterisation/test-data/Phase2Message.xml.njk
The HO200109 exception can be raised with a number of different combination of operations that aren't valid. These combination of operations can be raised with different combinations of offence result types.
For Core, this happens in [`validateOperations`](https://github.com/ministryofjustice/bichard7-next-core/blob/main/packages/core/phase2/lib/getOperationSequence/validateOperations.ts) and we check for different combination of operations in 5 different places.
The invalid combination of operations for HO200109 are:
1. APPHRD and DISARR
2. APPHRD and NEWREM (with and without remand court case references)
3. APPHRD and PENHRG
4. APPHRD and SENDEF
5. APPHRD and SUBVAR
6. APPHRD and COMSEN
7. SENDEF and COMSEN
8. SUBVAR and PENHRG
9. Duplicated APPHRD, COMSEN, SENDEF, SUBVAR and DISARR
The …
=> Add HO200109 characterisation tests

characterisation/exceptions/HO200115.test.ts
- HO200115 can be generated when a combination of PENHRG and DISARR operations or DISARR and SUBVAR operations.
- PENHRG and DISARR isn't possible because they conflict on fixed penalty.
- There are many different combinations of offence result types that can generate a DISARR and SUBVAR operation. These are all tested.
https://dsdmoj.atlassian.net/browse/BICAWS7-3053
=> Add HO200115 characterisation tests

.circleci/config.yml
We renamed the Docker Compose service in https://github.com/ministryofjustice/bichard7-next-core/pull/936.
https://dsdmoj.atlassian.net/browse/BICAWS7-2994
=> Update CI with Phase 2 message forwarder
