ministryofjustice/bichard7-next-tests

- steps/auditLogging.js
- utils/Poller.js
- Updated `Poller` to log the running time
- Updated `auditLogging` step to log the events found against the message when it fails.
> Audit logging log more info

- steps/ui.js
Opens the filter sidebar before clicking the search box
> Fix filtering in by record name in the new UI

- characterisation/helpers/mockRecordInPnc.ts
- helpers/Phase1Bucket.js
- helpers/PostgresHelper.js
- scripts/generate-phase1-comparison.js
- steps/message.js
- steps/world.js
- utils/defaults.js
Also adds a script to generate new and improved comparison files
> Enable the tests to be run against core using MESSAGE_ENTRY_POINT=s3phase1

- .github/workflows/update-npm-deps.yml
- package-lock.json
- package.json
This PR is to notify when the `update npm dependencies` script fails. It alerts the `moj-cjse-bichard-alerts` channel
> GitHub action alert

- features/011a-nppa-redirection/test.feature
- features/329-trigger-exclusion-rules/test.feature
- steps/ui.js
Add new UI tests for
- [011a-nppa-redirection](https://github.com/ministryofjustice/bichard7-next-tests/pull/351/commits/b42f22909fc69e794ddbb1da6cf33fa62ea83baa)
- [329-trigger-exclusion-rules](https://github.com/ministryofjustice/bichard7-next-tests/pull/351/commits/114e13c6c310990c2f7330348edf47450518196a)
> Add redirection and excluded trigger tests for new UI

- features/201-unfit-to-plead/test.feature
- features/202a-breach-further-offence/test.feature
- features/202b-breach-further-offence/test.feature
- features/204-removal-of-qualifiers/test.feature
- features/208-victim-surcharge/test.feature
- features/209-court-offence-not-added-to-pnc/test.feature
- features/210-restraining-order/test.feature
- features/212-electronic-tagging/test.feature
- features/213-offences-taken-into-consideration/test.feature
- features/217-youth-rehab-curfew/test.feature
- features/218-bail-breach-admits-plea/test.feature
- features/221-offences-added-in-court/test.feature
- features/228-adding-updating-offences/test.feature
- utils/dummyUserData.js
Switched on a number of test between 200-228. There are some failing in between and there will be a follow up PR with them fixed
> Add passing new UI test for 200-228

- features/169-stop-list-some-offences/test.feature
- features/174-partial-match-stop-list/test.feature
- features/197-offence-withdrawn/test.feature
> added more e2e tests to newUI

- package.json
- step-definitions/utils/auth.js
- step-definitions/utils/ui.js
- step-definitions/utils/waitForRecord.js
- utils/puppeteer-utils.js
This PR updates the NextUI steps to work with the recent changes in UI repo.
> Nextui steps update

- features/011a-nppa-redirection/test.feature
- step-definitions/utils/ui.js
PR to re-enable the test 011a for NextUI.
> Enable test 011a for NextUI

- step-definitions/utils/ui.js
BTP force name has been renamed in the latest standing data package. This PR updates the test to find and select the new name using the standing data.
> Update BTP force name for reallocation

- .circleci/config.yml
- helpers/BrowserHelper.js
- scripts/run_test_chunk.sh
- Store test output
- Set the screen size properly (!)
> Test improvements

- .circleci/config.yml
- .puppeteerrc.cjs
- scripts/run_test_chunk.sh
Also implements node-orb for managing dependency caching.
> Better test splitting

- helpers/BrowserHelper.js
Keep puppeteer open between tests instead of opening it each time
> Speed up the e2e tests

- .circleci/config.yml
- features/013-extra-offence-on-pnc/test.feature
- features/035-offence-category/test.feature
- features/142-trigger-reallocation/test.feature
- features/291-non-police-prosecution-court-hearing-is-ignored/test.feature
- features/300-results-already-on-pnc/test.feature
- features/302-incorrectly-reused-asn/test.feature
- features/401c-cp-amend-reshare/test.feature
- features/500-case-lock-events/test.feature
- features/501-trigger-resolved-events/test.feature
- features/502-reallocation-events/test.feature
- features/506-ignored-reopened-statutory-declaration/test.feature
- step-definitions/nextui.steps.js
- step-definitions/old-cucumber-js.steps.js
- utils/config.js
Also, remove @AuditLog tags as we don't need them
> Remove the test for conductor since we don't mark as resolved there now.

- features/506-ignored-reopened-statutory-declaration/test.feature
- tsconfig.json
Fixes the ES target for characterisation tests
Fixes duplicate test name for test 506
> Small bug fixes

- .vscode/settings.json
- Dockerfile
- README.md
Should fix the deployment pipeline.
> Fix references to step-definitions

- characterisation/exceptions/HO200108.test.ts
- characterisation/test-data/AnnotatedHearingOutcome-HO200108.xml.njk
- characterisation/test-data/PncUpdateDataset-HO200108.xml.njk
- tsconfig.json
https://dsdmoj.atlassian.net/browse/BICAWS7-3022
> Add HO200108 characterisation tests

- .circleci/config.yml
- characterisation/exceptions/HO200100.test.ts
- characterisation/exceptions/HO200101.test.ts
- characterisation/exceptions/HO200108.test.ts
- characterisation/helpers/processMessageBichard.ts
- characterisation/helpers/processMessageCore.ts
- characterisation/test-data/HO200100/aho-no-pnc-adjudication-exists.xml.njk
- characterisation/test-data/HO200100/aho-pnc-adjudication-exists.xml.njk
- characterisation/test-data/HO200100/pud-no-pnc-adjudication-exists.xml.njk
- characterisation/test-data/HO200100/pud-pnc-adjudication-exists.xml.njk
- characterisation/test-data/HO200101/pud-adjournment-with-judgement.xml.njk
- characterisation/test-data/HO200101/pud-judgement-with-final-result.xml.njk
- characterisation/test-data/HO200108/pud-adjournment-with-judgement.xml.njk
- characterisation/test-data/HO200108/pud-judgement-with-final-result.xml.njk
https://dsdmoj.atlassian.net/browse/BICAWS7-3049
> Add HO200100 characterisation tests

- characterisation/exceptions/HO200107.test.ts
- characterisation/test-data/HO200107/aho-no-pnc-adjudication-exists.xml.njk
- characterisation/test-data/HO200107/aho-pnc-adjudication-exists.xml.njk
- characterisation/test-data/HO200107/pud-no-pnc-adjudication-exists.xml.njk
- characterisation/test-data/HO200107/pud-pnc-adjudication-exists.xml.njk
https://dsdmoj.atlassian.net/browse/BICAWS7-3050
> Add HO200107 characterisation tests

- characterisation/exceptions/HO200101.test.ts
- characterisation/exceptions/HO200106.test.ts
- characterisation/exceptions/HO200108.test.ts
- characterisation/test-data/HO200106/aho-pnc-adjudication-exists-and-added-by-the-court.xml.njk
- characterisation/test-data/HO200106/aho-pnc-adjudication-exists.xml.njk
- characterisation/test-data/HO200106/aho-sentence.xml.njk
- characterisation/test-data/HO200106/pud-sentence.xml.njk
https://dsdmoj.atlassian.net/browse/BICAWS7-3051
> Add HO200106 characterisation tests

- characterisation/exceptions/HO200110.test.ts
- characterisation/exceptions/HO200112.test.ts
- characterisation/test-data/HO200110/aho-not-recordable-on-pnc.xml.njk
- characterisation/test-data/HO200110/aho-recordable-on-pnc.xml.njk
- characterisation/test-data/HO200110/pud-recordable-on-pnc.xml.njk
https://dsdmoj.atlassian.net/browse/BICAWS7-3045
> Add HO200110 characterisation tests

- characterisation/exceptions/HO200212.test.ts
https://dsdmoj.atlassian.net/browse/BICAWS7-3026
> Add HO200212 characterisation tests

- characterisation/exceptions/HO200200.test.ts
- characterisation/helpers/generatePhase2Message.ts
- characterisation/test-data/Phase2Message.xml.njk
https://dsdmoj.atlassian.net/browse/BICAWS7-3041
> Add HO200200 characterisation tests

- characterisation/exceptions/HO200205.test.ts
- characterisation/helpers/errorPaths.ts
- characterisation/helpers/generatePhase2Message.ts
- characterisation/test-data/Phase2Message.xml.njk
https://dsdmoj.atlassian.net/browse/BICAWS7-3042
> Add HO200205 characterisation tests

- characterisation/exceptions/HO200201.test.ts
- characterisation/exceptions/HO200202.test.ts
- characterisation/helpers/errorPaths.ts
- characterisation/helpers/generatePhase2Message.ts
- characterisation/test-data/Phase2Message.xml.njk
https://dsdmoj.atlassian.net/browse/BICAWS7-3044
> Add HO200201 characterisation tests

- characterisation/exceptions/HO200121.test.ts
- characterisation/helpers/generatePhase2Message.ts
- characterisation/test-data/Phase2Message.xml.njk
https://dsdmoj.atlassian.net/browse/BICAWS7-3047
> Add HO200121 characterisation tests

- scripts/uat-data/README.md
Update pnc-emulator load balancer DNS on read me to seed cases on UAT environment
> Update pnc-emulator load balancer DNS on read-me

- characterisation/test-data/Phase2Message.xml.njk
- characterisation/triggers/TRPS0008.test.ts
- characterisation/triggers/TRPS0011.test.ts
- characterisation/types/TriggerCode.ts
https://dsdmoj.atlassian.net/browse/BICAWS7-3030
> Add TRPS0008 characterisation tests
